package com.blueforge.entity;

public enum ProjectVersionStatus {
    AWAITING_ANSWERS,
    REQUIREMENTS_GENERATED,
    EPICS_GENERATED,
    USER_STORIES_GENERATED,
    TASKS_GENERATED,
    ARCHITECTURE_GENERATED
}
