/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { apiFetch } from './mutator';
export interface CreateProjectRequest {
  /** @minLength 1 */
  name?: string;
  /** @minLength 1 */
  ideaDescription?: string;
}

export interface ClarifyingQuestionResponse {
  id?: number;
  questionText?: string;
  orderIndex?: number;
  answerText?: string;
}

export interface CreateProjectResponse {
  projectId?: number;
  versionId?: number;
  questions?: ClarifyingQuestionResponse[];
}

export interface EpicResponse {
  id?: number;
  title?: string;
  description?: string;
  orderIndex?: number;
}

export type ProjectVersionResponseStatus = typeof ProjectVersionResponseStatus[keyof typeof ProjectVersionResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectVersionResponseStatus = {
  AWAITING_ANSWERS: 'AWAITING_ANSWERS',
  REQUIREMENTS_GENERATED: 'REQUIREMENTS_GENERATED',
  EPICS_GENERATED: 'EPICS_GENERATED',
  USER_STORIES_GENERATED: 'USER_STORIES_GENERATED',
  TASKS_GENERATED: 'TASKS_GENERATED',
} as const;

export interface ProjectVersionResponse {
  versionId?: number;
  projectId?: number;
  versionNumber?: number;
  ideaSnapshot?: string;
  changeDescription?: string;
  status?: ProjectVersionResponseStatus;
  questions?: ClarifyingQuestionResponse[];
  requirements?: RequirementResponse[];
  epics?: EpicResponse[];
  userStories?: UserStoryResponse[];
  tasks?: TaskResponse[];
}

export type RequirementResponseType = typeof RequirementResponseType[keyof typeof RequirementResponseType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequirementResponseType = {
  FUNCTIONAL: 'FUNCTIONAL',
  NON_FUNCTIONAL: 'NON_FUNCTIONAL',
  CONSTRAINT: 'CONSTRAINT',
  ASSUMPTION: 'ASSUMPTION',
} as const;

export interface RequirementResponse {
  id?: number;
  type?: RequirementResponseType;
  title?: string;
  description?: string;
  orderIndex?: number;
}

export type TaskResponsePriority = typeof TaskResponsePriority[keyof typeof TaskResponsePriority];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaskResponsePriority = {
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
} as const;

export type TaskResponseEffortEstimate = typeof TaskResponseEffortEstimate[keyof typeof TaskResponseEffortEstimate];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaskResponseEffortEstimate = {
  S: 'S',
  M: 'M',
  L: 'L',
} as const;

export interface TaskResponse {
  id?: number;
  userStoryId?: number;
  title?: string;
  description?: string;
  priority?: TaskResponsePriority;
  effortEstimate?: TaskResponseEffortEstimate;
  orderIndex?: number;
}

export interface UserStoryResponse {
  id?: number;
  epicId?: number;
  title?: string;
  description?: string;
  acceptanceCriteria?: string;
  orderIndex?: number;
}

export interface AnswerRequest {
  questionId: number;
  /** @minLength 1 */
  answerText?: string;
}

export interface SubmitAnswersRequest {
  /** @minItems 1 */
  answers?: AnswerRequest[];
}

export interface UpdateUserStoryRequest {
  /** @minLength 1 */
  title?: string;
  /** @minLength 1 */
  description?: string;
  /** @minLength 1 */
  acceptanceCriteria?: string;
}

export interface UpdateTaskRequest {
  /** @minLength 1 */
  title?: string;
  /** @minLength 1 */
  description?: string;
}

export interface UpdateRequirementRequest {
  /** @minLength 1 */
  title?: string;
  /** @minLength 1 */
  description?: string;
}

export interface UpdateEpicRequest {
  /** @minLength 1 */
  title?: string;
  /** @minLength 1 */
  description?: string;
}

export type ProjectSummaryResponseLatestStatus = typeof ProjectSummaryResponseLatestStatus[keyof typeof ProjectSummaryResponseLatestStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectSummaryResponseLatestStatus = {
  AWAITING_ANSWERS: 'AWAITING_ANSWERS',
  REQUIREMENTS_GENERATED: 'REQUIREMENTS_GENERATED',
  EPICS_GENERATED: 'EPICS_GENERATED',
  USER_STORIES_GENERATED: 'USER_STORIES_GENERATED',
  TASKS_GENERATED: 'TASKS_GENERATED',
} as const;

export interface ProjectSummaryResponse {
  id?: number;
  name?: string;
  createdAt?: string;
  latestVersionNumber?: number;
  latestStatus?: ProjectSummaryResponseLatestStatus;
}

export interface ProjectDetailResponse {
  id?: number;
  name?: string;
  createdAt?: string;
  versions?: ProjectVersionSummaryResponse[];
}

export type ProjectVersionSummaryResponseStatus = typeof ProjectVersionSummaryResponseStatus[keyof typeof ProjectVersionSummaryResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectVersionSummaryResponseStatus = {
  AWAITING_ANSWERS: 'AWAITING_ANSWERS',
  REQUIREMENTS_GENERATED: 'REQUIREMENTS_GENERATED',
  EPICS_GENERATED: 'EPICS_GENERATED',
  USER_STORIES_GENERATED: 'USER_STORIES_GENERATED',
  TASKS_GENERATED: 'TASKS_GENERATED',
} as const;

export interface ProjectVersionSummaryResponse {
  versionId?: number;
  versionNumber?: number;
  status?: ProjectVersionSummaryResponseStatus;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getListProjectsUrl = () => {


  

  return `/api/projects`
}

export const listProjects = async ( options?: RequestInit): Promise<ProjectSummaryResponse[]> => {
  
  return apiFetch<ProjectSummaryResponse[]>(getListProjectsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListProjectsQueryKey = () => {
    return [
    `/api/projects`
    ] as const;
    }

    
export const getListProjectsQueryOptions = <TData = Awaited<ReturnType<typeof listProjects>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListProjectsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listProjects>>> = ({ signal }) => listProjects({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListProjectsQueryResult = NonNullable<Awaited<ReturnType<typeof listProjects>>>
export type ListProjectsQueryError = unknown


export function useListProjects<TData = Awaited<ReturnType<typeof listProjects>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProjects>>,
          TError,
          Awaited<ReturnType<typeof listProjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProjects<TData = Awaited<ReturnType<typeof listProjects>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProjects>>,
          TError,
          Awaited<ReturnType<typeof listProjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProjects<TData = Awaited<ReturnType<typeof listProjects>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListProjects<TData = Awaited<ReturnType<typeof listProjects>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListProjectsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getCreateProjectUrl = () => {


  

  return `/api/projects`
}

export const createProject = async (createProjectRequest: CreateProjectRequest, options?: RequestInit): Promise<CreateProjectResponse> => {
  
  return apiFetch<CreateProjectResponse>(getCreateProjectUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createProjectRequest,)
  }
);}




export const getCreateProjectMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProject>>, TError,{data: CreateProjectRequest}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createProject>>, TError,{data: CreateProjectRequest}, TContext> => {

const mutationKey = ['createProject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProject>>, {data: CreateProjectRequest}> = (props) => {
          const {data} = props ?? {};

          return  createProject(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateProjectMutationResult = NonNullable<Awaited<ReturnType<typeof createProject>>>
    export type CreateProjectMutationBody = CreateProjectRequest
    export type CreateProjectMutationError = unknown

    export const useCreateProject = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProject>>, TError,{data: CreateProjectRequest}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProject>>,
        TError,
        {data: CreateProjectRequest},
        TContext
      > => {

      const mutationOptions = getCreateProjectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getGenerateUserStoriesUrl = (projectId: number,
    versionNumber: number,) => {


  

  return `/api/projects/${projectId}/versions/${versionNumber}/user-stories`
}

export const generateUserStories = async (projectId: number,
    versionNumber: number, options?: RequestInit): Promise<ProjectVersionResponse> => {
  
  return apiFetch<ProjectVersionResponse>(getGenerateUserStoriesUrl(projectId,versionNumber),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getGenerateUserStoriesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateUserStories>>, TError,{projectId: number;versionNumber: number}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof generateUserStories>>, TError,{projectId: number;versionNumber: number}, TContext> => {

const mutationKey = ['generateUserStories'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof generateUserStories>>, {projectId: number;versionNumber: number}> = (props) => {
          const {projectId,versionNumber} = props ?? {};

          return  generateUserStories(projectId,versionNumber,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GenerateUserStoriesMutationResult = NonNullable<Awaited<ReturnType<typeof generateUserStories>>>
    
    export type GenerateUserStoriesMutationError = unknown

    export const useGenerateUserStories = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateUserStories>>, TError,{projectId: number;versionNumber: number}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof generateUserStories>>,
        TError,
        {projectId: number;versionNumber: number},
        TContext
      > => {

      const mutationOptions = getGenerateUserStoriesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getGenerateTasksUrl = (projectId: number,
    versionNumber: number,) => {


  

  return `/api/projects/${projectId}/versions/${versionNumber}/tasks`
}

export const generateTasks = async (projectId: number,
    versionNumber: number, options?: RequestInit): Promise<ProjectVersionResponse> => {
  
  return apiFetch<ProjectVersionResponse>(getGenerateTasksUrl(projectId,versionNumber),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getGenerateTasksMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateTasks>>, TError,{projectId: number;versionNumber: number}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof generateTasks>>, TError,{projectId: number;versionNumber: number}, TContext> => {

const mutationKey = ['generateTasks'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof generateTasks>>, {projectId: number;versionNumber: number}> = (props) => {
          const {projectId,versionNumber} = props ?? {};

          return  generateTasks(projectId,versionNumber,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GenerateTasksMutationResult = NonNullable<Awaited<ReturnType<typeof generateTasks>>>
    
    export type GenerateTasksMutationError = unknown

    export const useGenerateTasks = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateTasks>>, TError,{projectId: number;versionNumber: number}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof generateTasks>>,
        TError,
        {projectId: number;versionNumber: number},
        TContext
      > => {

      const mutationOptions = getGenerateTasksMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getGenerateEpicsUrl = (projectId: number,
    versionNumber: number,) => {


  

  return `/api/projects/${projectId}/versions/${versionNumber}/epics`
}

export const generateEpics = async (projectId: number,
    versionNumber: number, options?: RequestInit): Promise<ProjectVersionResponse> => {
  
  return apiFetch<ProjectVersionResponse>(getGenerateEpicsUrl(projectId,versionNumber),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getGenerateEpicsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateEpics>>, TError,{projectId: number;versionNumber: number}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof generateEpics>>, TError,{projectId: number;versionNumber: number}, TContext> => {

const mutationKey = ['generateEpics'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof generateEpics>>, {projectId: number;versionNumber: number}> = (props) => {
          const {projectId,versionNumber} = props ?? {};

          return  generateEpics(projectId,versionNumber,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GenerateEpicsMutationResult = NonNullable<Awaited<ReturnType<typeof generateEpics>>>
    
    export type GenerateEpicsMutationError = unknown

    export const useGenerateEpics = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateEpics>>, TError,{projectId: number;versionNumber: number}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof generateEpics>>,
        TError,
        {projectId: number;versionNumber: number},
        TContext
      > => {

      const mutationOptions = getGenerateEpicsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getSubmitAnswersUrl = (projectId: number,
    versionNumber: number,) => {


  

  return `/api/projects/${projectId}/versions/${versionNumber}/answers`
}

export const submitAnswers = async (projectId: number,
    versionNumber: number,
    submitAnswersRequest: SubmitAnswersRequest, options?: RequestInit): Promise<ProjectVersionResponse> => {
  
  return apiFetch<ProjectVersionResponse>(getSubmitAnswersUrl(projectId,versionNumber),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      submitAnswersRequest,)
  }
);}




export const getSubmitAnswersMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitAnswers>>, TError,{projectId: number;versionNumber: number;data: SubmitAnswersRequest}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof submitAnswers>>, TError,{projectId: number;versionNumber: number;data: SubmitAnswersRequest}, TContext> => {

const mutationKey = ['submitAnswers'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof submitAnswers>>, {projectId: number;versionNumber: number;data: SubmitAnswersRequest}> = (props) => {
          const {projectId,versionNumber,data} = props ?? {};

          return  submitAnswers(projectId,versionNumber,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SubmitAnswersMutationResult = NonNullable<Awaited<ReturnType<typeof submitAnswers>>>
    export type SubmitAnswersMutationBody = SubmitAnswersRequest
    export type SubmitAnswersMutationError = unknown

    export const useSubmitAnswers = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitAnswers>>, TError,{projectId: number;versionNumber: number;data: SubmitAnswersRequest}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof submitAnswers>>,
        TError,
        {projectId: number;versionNumber: number;data: SubmitAnswersRequest},
        TContext
      > => {

      const mutationOptions = getSubmitAnswersMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getUpdateUserStoryUrl = (userStoryId: number,) => {


  

  return `/api/user-stories/${userStoryId}`
}

export const updateUserStory = async (userStoryId: number,
    updateUserStoryRequest: UpdateUserStoryRequest, options?: RequestInit): Promise<UserStoryResponse> => {
  
  return apiFetch<UserStoryResponse>(getUpdateUserStoryUrl(userStoryId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateUserStoryRequest,)
  }
);}




export const getUpdateUserStoryMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserStory>>, TError,{userStoryId: number;data: UpdateUserStoryRequest}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateUserStory>>, TError,{userStoryId: number;data: UpdateUserStoryRequest}, TContext> => {

const mutationKey = ['updateUserStory'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUserStory>>, {userStoryId: number;data: UpdateUserStoryRequest}> = (props) => {
          const {userStoryId,data} = props ?? {};

          return  updateUserStory(userStoryId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserStoryMutationResult = NonNullable<Awaited<ReturnType<typeof updateUserStory>>>
    export type UpdateUserStoryMutationBody = UpdateUserStoryRequest
    export type UpdateUserStoryMutationError = unknown

    export const useUpdateUserStory = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserStory>>, TError,{userStoryId: number;data: UpdateUserStoryRequest}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateUserStory>>,
        TError,
        {userStoryId: number;data: UpdateUserStoryRequest},
        TContext
      > => {

      const mutationOptions = getUpdateUserStoryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getUpdateTaskUrl = (taskId: number,) => {


  

  return `/api/tasks/${taskId}`
}

export const updateTask = async (taskId: number,
    updateTaskRequest: UpdateTaskRequest, options?: RequestInit): Promise<TaskResponse> => {
  
  return apiFetch<TaskResponse>(getUpdateTaskUrl(taskId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateTaskRequest,)
  }
);}




export const getUpdateTaskMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTask>>, TError,{taskId: number;data: UpdateTaskRequest}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateTask>>, TError,{taskId: number;data: UpdateTaskRequest}, TContext> => {

const mutationKey = ['updateTask'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTask>>, {taskId: number;data: UpdateTaskRequest}> = (props) => {
          const {taskId,data} = props ?? {};

          return  updateTask(taskId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateTaskMutationResult = NonNullable<Awaited<ReturnType<typeof updateTask>>>
    export type UpdateTaskMutationBody = UpdateTaskRequest
    export type UpdateTaskMutationError = unknown

    export const useUpdateTask = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTask>>, TError,{taskId: number;data: UpdateTaskRequest}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTask>>,
        TError,
        {taskId: number;data: UpdateTaskRequest},
        TContext
      > => {

      const mutationOptions = getUpdateTaskMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getUpdateRequirementUrl = (requirementId: number,) => {


  

  return `/api/requirements/${requirementId}`
}

export const updateRequirement = async (requirementId: number,
    updateRequirementRequest: UpdateRequirementRequest, options?: RequestInit): Promise<RequirementResponse> => {
  
  return apiFetch<RequirementResponse>(getUpdateRequirementUrl(requirementId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateRequirementRequest,)
  }
);}




export const getUpdateRequirementMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRequirement>>, TError,{requirementId: number;data: UpdateRequirementRequest}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateRequirement>>, TError,{requirementId: number;data: UpdateRequirementRequest}, TContext> => {

const mutationKey = ['updateRequirement'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateRequirement>>, {requirementId: number;data: UpdateRequirementRequest}> = (props) => {
          const {requirementId,data} = props ?? {};

          return  updateRequirement(requirementId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateRequirementMutationResult = NonNullable<Awaited<ReturnType<typeof updateRequirement>>>
    export type UpdateRequirementMutationBody = UpdateRequirementRequest
    export type UpdateRequirementMutationError = unknown

    export const useUpdateRequirement = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRequirement>>, TError,{requirementId: number;data: UpdateRequirementRequest}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateRequirement>>,
        TError,
        {requirementId: number;data: UpdateRequirementRequest},
        TContext
      > => {

      const mutationOptions = getUpdateRequirementMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getUpdateEpicUrl = (epicId: number,) => {


  

  return `/api/epics/${epicId}`
}

export const updateEpic = async (epicId: number,
    updateEpicRequest: UpdateEpicRequest, options?: RequestInit): Promise<EpicResponse> => {
  
  return apiFetch<EpicResponse>(getUpdateEpicUrl(epicId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateEpicRequest,)
  }
);}




export const getUpdateEpicMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateEpic>>, TError,{epicId: number;data: UpdateEpicRequest}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateEpic>>, TError,{epicId: number;data: UpdateEpicRequest}, TContext> => {

const mutationKey = ['updateEpic'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateEpic>>, {epicId: number;data: UpdateEpicRequest}> = (props) => {
          const {epicId,data} = props ?? {};

          return  updateEpic(epicId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateEpicMutationResult = NonNullable<Awaited<ReturnType<typeof updateEpic>>>
    export type UpdateEpicMutationBody = UpdateEpicRequest
    export type UpdateEpicMutationError = unknown

    export const useUpdateEpic = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateEpic>>, TError,{epicId: number;data: UpdateEpicRequest}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateEpic>>,
        TError,
        {epicId: number;data: UpdateEpicRequest},
        TContext
      > => {

      const mutationOptions = getUpdateEpicMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getGetProjectUrl = (projectId: number,) => {


  

  return `/api/projects/${projectId}`
}

export const getProject = async (projectId: number, options?: RequestInit): Promise<ProjectDetailResponse> => {
  
  return apiFetch<ProjectDetailResponse>(getGetProjectUrl(projectId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetProjectQueryKey = (projectId?: number,) => {
    return [
    `/api/projects/${projectId}`
    ] as const;
    }

    
export const getGetProjectQueryOptions = <TData = Awaited<ReturnType<typeof getProject>>, TError = unknown>(projectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProjectQueryKey(projectId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProject>>> = ({ signal }) => getProject(projectId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(projectId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProjectQueryResult = NonNullable<Awaited<ReturnType<typeof getProject>>>
export type GetProjectQueryError = unknown


export function useGetProject<TData = Awaited<ReturnType<typeof getProject>>, TError = unknown>(
 projectId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProject>>,
          TError,
          Awaited<ReturnType<typeof getProject>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProject<TData = Awaited<ReturnType<typeof getProject>>, TError = unknown>(
 projectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProject>>,
          TError,
          Awaited<ReturnType<typeof getProject>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProject<TData = Awaited<ReturnType<typeof getProject>>, TError = unknown>(
 projectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetProject<TData = Awaited<ReturnType<typeof getProject>>, TError = unknown>(
 projectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProjectQueryOptions(projectId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getListVersionsUrl = (projectId: number,) => {


  

  return `/api/projects/${projectId}/versions`
}

export const listVersions = async (projectId: number, options?: RequestInit): Promise<ProjectVersionSummaryResponse[]> => {
  
  return apiFetch<ProjectVersionSummaryResponse[]>(getListVersionsUrl(projectId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListVersionsQueryKey = (projectId?: number,) => {
    return [
    `/api/projects/${projectId}/versions`
    ] as const;
    }

    
export const getListVersionsQueryOptions = <TData = Awaited<ReturnType<typeof listVersions>>, TError = unknown>(projectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVersions>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListVersionsQueryKey(projectId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listVersions>>> = ({ signal }) => listVersions(projectId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(projectId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listVersions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListVersionsQueryResult = NonNullable<Awaited<ReturnType<typeof listVersions>>>
export type ListVersionsQueryError = unknown


export function useListVersions<TData = Awaited<ReturnType<typeof listVersions>>, TError = unknown>(
 projectId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVersions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVersions>>,
          TError,
          Awaited<ReturnType<typeof listVersions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListVersions<TData = Awaited<ReturnType<typeof listVersions>>, TError = unknown>(
 projectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVersions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVersions>>,
          TError,
          Awaited<ReturnType<typeof listVersions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListVersions<TData = Awaited<ReturnType<typeof listVersions>>, TError = unknown>(
 projectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVersions>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListVersions<TData = Awaited<ReturnType<typeof listVersions>>, TError = unknown>(
 projectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVersions>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListVersionsQueryOptions(projectId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getGetProjectVersionUrl = (projectId: number,
    versionNumber: number,) => {


  

  return `/api/projects/${projectId}/versions/${versionNumber}`
}

export const getProjectVersion = async (projectId: number,
    versionNumber: number, options?: RequestInit): Promise<ProjectVersionResponse> => {
  
  return apiFetch<ProjectVersionResponse>(getGetProjectVersionUrl(projectId,versionNumber),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetProjectVersionQueryKey = (projectId?: number,
    versionNumber?: number,) => {
    return [
    `/api/projects/${projectId}/versions/${versionNumber}`
    ] as const;
    }

    
export const getGetProjectVersionQueryOptions = <TData = Awaited<ReturnType<typeof getProjectVersion>>, TError = unknown>(projectId: number,
    versionNumber: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectVersion>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProjectVersionQueryKey(projectId,versionNumber);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProjectVersion>>> = ({ signal }) => getProjectVersion(projectId,versionNumber, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(projectId && versionNumber), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProjectVersion>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProjectVersionQueryResult = NonNullable<Awaited<ReturnType<typeof getProjectVersion>>>
export type GetProjectVersionQueryError = unknown


export function useGetProjectVersion<TData = Awaited<ReturnType<typeof getProjectVersion>>, TError = unknown>(
 projectId: number,
    versionNumber: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectVersion>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectVersion>>,
          TError,
          Awaited<ReturnType<typeof getProjectVersion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProjectVersion<TData = Awaited<ReturnType<typeof getProjectVersion>>, TError = unknown>(
 projectId: number,
    versionNumber: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectVersion>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectVersion>>,
          TError,
          Awaited<ReturnType<typeof getProjectVersion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProjectVersion<TData = Awaited<ReturnType<typeof getProjectVersion>>, TError = unknown>(
 projectId: number,
    versionNumber: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectVersion>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetProjectVersion<TData = Awaited<ReturnType<typeof getProjectVersion>>, TError = unknown>(
 projectId: number,
    versionNumber: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectVersion>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProjectVersionQueryOptions(projectId,versionNumber,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}
